{{- if .Values.workerHn.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "flux.fullname" . }}-worker-hn
  labels:
    {{- include "flux.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker-hn
spec:
  schedule: {{ .Values.workerHn.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            {{- include "flux.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: worker-hn
        spec:
          {{- with .Values.workerHn.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- include "flux.imagePullSecrets" . | nindent 10 }}
          restartPolicy: OnFailure
          containers:
            - name: worker-hn
              image: "{{ if .Values.global.imageRegistry }}{{ .Values.global.imageRegistry }}/{{ end }}{{ .Values.workerHn.image.repository }}:{{ .Values.workerHn.image.tag }}"
              imagePullPolicy: {{ .Values.global.imagePullPolicy }}
              env:
                - name: WORKER_MODE
                  value: "cronjob"
                - name: HN_MIN_SCORE
                  value: {{ .Values.workerHn.minScore | quote }}
              envFrom:
                - configMapRef:
                    name: {{ include "flux.fullname" . }}-config
                - secretRef:
                    name: {{ include "flux.secretName" . }}
              resources:
                {{- toYaml .Values.workerHn.resources | nindent 16 }}
{{- end }}
