{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flux.fullname" . }}-frontend
  labels:
    {{- include "flux.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flux.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
